---
- name: Update and upgrade packages on specific node using update-packages role
  hosts: pihole_nodes
  remote_user: pi
  become: yes
  roles:
    - update-packages

  tasks:
    - name: Run 'pihole -up' command
      command:
        cmd: /usr/local/bin/pihole -up
