---
- name: Update and upgrade packages on specific node using update-packages role
  hosts: pihole_nodes
  remote_user: pi
  become: yes
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter sudo password"
      private: yes
  roles:
    - update-packages

  tasks:
    - name: Run 'pihole -up' command
      command:
        cmd: /usr/local/bin/pihole -up
