{{- if .Values.cronSchedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
{{- include "ansible-job-chart.jobSpec" . | nindent 10 }}
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
spec:
  template:
    spec:
{{- include "ansible-job-chart.jobSpec" . | nindent 6 }}
{{- end }}