---
apiVersion: v1
kind: Secret
metadata:
  name: ansible-ssh-key
type: Opaque
data:
  id_rsa: |
{{ .Values.sshKey | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
stringData:
  inventory.ini: |
{{ .Values.inventorySecret | indent 4 }}
