{{- if .Values.truenasServers }}
apiVersion: v1
kind: Secret
metadata:
  name: truenas-config
type: Opaque
stringData:
  truenas-servers.yml: |
    servers:
    {{- range .Values.truenasServers }}
      - hostname: {{ .hostname }}
        token: {{ .token }}
        validate_certs: {{ .validate_certs }}
    {{- end }}
{{- end }}
