image:
  repository: pdmurray/ansible-update-pkgs
  tag: latest

cronSchedule: "" # By default, this is empty meaning it's a regular Job. If set, it'll be a CronJob.

playbook:
  name: "update-packages.yml"  # update-packages.yml, update-pihole.yml, reboot-nodes.yml, update-truenas-charts.yml
  extraArgs: ""  # Optional extra arguments you'd like to pass to the `ansible-playbook` command

sshKey: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  ...
  -----END OPENSSH PRIVATE KEY-----

inventorySecret: |
  [all:vars]
  ansible_become_password=**********

  [ubuntu_nodes]
  node1
  node2
  node3

  [ubuntu_nodes:vars]
  ansible_user=pdmurray

  [pihole_nodes]
  node4 ansible_user=root
  node5 ansible_user=pi
  ...
